/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_edd.GUI;

/**
 *
 * @author ADRIAN
 */
public class HistorialCitasGeneral extends javax.swing.JPanel {

    /**
     * Creates new form BuscarHistorialPaciente
     */
    public HistorialCitasGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comprobar = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ordenarPor = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese DNI o código de paciente:");

        jLabel17.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        jLabel17.setText("Actualizar datos de paciente");

        comprobar.setBackground(new java.awt.Color(1, 37, 70));
        comprobar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        comprobar.setForeground(new java.awt.Color(255, 255, 255));
        comprobar.setText("COMPROBAR");
        comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        jLabel18.setText("Historial de citas");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 626, 24));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID cita", "DNI", "Paciente", "Odontologo", "Motivo", "Fecha", "Hora", "Alergias", "Estado cita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, 730, 352));

        jLabel2.setText("Ordenar por");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        ordenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha", "Hora", "Alergias", "Estado" }));
        ordenarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPorActionPerformed(evt);
            }
        });
        add(ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprobarActionPerformed

    private void ordenarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordenarPorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprobar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JComboBox<String> ordenarPor;
    // End of variables declaration//GEN-END:variables
}
