/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_edd.GUI;

import com.mycompany.proyecto_edd.Cita;
import java.util.Stack;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADRIAN
 */
public class HistorialCitasGeneral extends javax.swing.JPanel {

    /**
     * Creates new form BuscarHistorialPaciente
     */
    public HistorialCitasGeneral() {
        initComponents();
        cargarCitasEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void cargarCitasEnTabla() {
        Stack<Cita> listaCitas = Cita.cargarCitas();  

        DefaultTableModel modelo = (DefaultTableModel) tablaCitas.getModel();
        modelo.setRowCount(0);  // Limpiar la tabla antes de agregar nuevas filas

        for (Cita cita : listaCitas) {
            Object[] fila = {
                cita.getId(),
                cita.getPaciente().getDni(),
                cita.getPaciente().getNombres(),
                cita.getOdontologo().getNombres(),
                cita.getMotivo(),
                cita.getFecha().fechaAbreviada(),
                cita.getHora().horaAbreviada(),
                cita.getPaciente().getAlergia(),
                cita.getEstadoCita()
            };

            modelo.addRow(fila);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ordenarPor = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(1, 138, 190));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Historial de citas");

        tablaCitas.setBackground(new java.awt.Color(240, 241, 241));
        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID cita", "DNI", "Paciente", "Odontologo", "Motivo", "Fecha", "Hora", "Alergias", "Estado cita"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaCitas.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaCitas);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ordenar por:");

        ordenarPor.setBackground(new java.awt.Color(2, 69, 122));
        ordenarPor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ordenarPor.setForeground(new java.awt.Color(255, 255, 255));
        ordenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Fecha Ascendente", "Fecha Descendente", "Estado Pendiente", "Estado Cancelado", "Estado Terminado" }));
        ordenarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ordenarPor, 0, 112, Short.MAX_VALUE)
                        .addGap(508, 508, 508))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordenarPor))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ordenarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPorActionPerformed
        String seleccion = ordenarPor.getSelectedItem().toString();
        Stack<Cita> citas = Cita.cargarCitas();
        Stack<Cita> citasOrdenadas = new Stack<>();
        
        switch (seleccion) {
            case "Fecha Ascendente":
                citasOrdenadas = ordenarPorFechaAscendente(citas);
                break;
            case "Fecha Descendente":
                citasOrdenadas = ordenarPorFechaDescendente(citas);
                break;
            case "Estado Pendiente":
                citasOrdenadas = ordenarPorEstado(citas, "Pendiente");
                citasOrdenadas = ordenarPorId(citasOrdenadas);
                break;
            case "Estado Cancelado":
                citasOrdenadas = ordenarPorEstado(citas, "Cancelada");
                citasOrdenadas = ordenarPorId(citasOrdenadas);
                break;
            case "Estado Terminado":
                citasOrdenadas = ordenarPorEstado(citas,"Terminado");
                citasOrdenadas = ordenarPorId(citasOrdenadas);
                break;
            default:
                citasOrdenadas = citas;  // No hace nada si no se selecciona una opción válida
        }
        
        // Limpiar la tabla antes de agregar nuevas filas
        DefaultTableModel modelo = (DefaultTableModel) tablaCitas.getModel();
        modelo.setRowCount(0);

        // Añadir las citas ordenadas a la tabla
        for (Cita cita : citasOrdenadas) {
            Object[] fila = {
                cita.getId(),
                cita.getPaciente().getDni(),
                cita.getPaciente().getNombres(),
                cita.getOdontologo().getNombres(),
                cita.getMotivo(),
                cita.getFecha().fechaAbreviada(),
                cita.getHora().horaAbreviada(),
                cita.getPaciente().getAlergia(),
                cita.getEstadoCita()
            };
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_ordenarPorActionPerformed
    private Stack<Cita> ordenarPorId(Stack<Cita> citas) {
        Stack<Cita> pilaOrdenada = new Stack<>();
        while (!citas.isEmpty()) {
            Cita citaActual = citas.pop();
            // Insertar en la pila ordenada de manera que los IDs estén en orden ascendente
            while (!pilaOrdenada.isEmpty() && Integer.parseInt(pilaOrdenada.peek().getId()) > Integer.parseInt(citaActual.getId())) {
                citas.push(pilaOrdenada.pop());
            }
            pilaOrdenada.push(citaActual);
        }
        return pilaOrdenada;
    }
    // Ordenar las citas por fecha ascendente
    private Stack<Cita> ordenarPorFechaAscendente(Stack<Cita> citas) {
        Stack<Cita> pilaOrdenada = new Stack<>();
        while (!citas.isEmpty()) {
            Cita citaActual = citas.pop();
            // Insertar en la pila ordenada de manera que las fechas estén en orden ascendente
            while (!pilaOrdenada.isEmpty() && pilaOrdenada.peek().getFecha().compararFecha(citaActual.getFecha()) > 0) {
                citas.push(pilaOrdenada.pop());
            }
            pilaOrdenada.push(citaActual);
        }
        return pilaOrdenada;
    }

    // Ordenar las citas por fecha descendente
    private Stack<Cita> ordenarPorFechaDescendente(Stack<Cita> citas) {
        Stack<Cita> pilaOrdenada = new Stack<>();
        while (!citas.isEmpty()) {
            Cita citaActual = citas.pop();
            // Insertar en la pila ordenada de manera que las fechas estén en orden descendente
            while (!pilaOrdenada.isEmpty() && pilaOrdenada.peek().getFecha().compararFecha(citaActual.getFecha()) < 0) {
                citas.push(pilaOrdenada.pop());
            }
            pilaOrdenada.push(citaActual);
        }
        return pilaOrdenada;
    }

    // Ordenar las citas por estado
    private Stack<Cita> ordenarPorEstado(Stack<Cita> citas, String estado) {
        Stack<Cita> pilaFiltrada = new Stack<>();
        // Filtrar las citas según el estado
        while (!citas.isEmpty()) {
            Cita cita = citas.pop();
            if (cita.getEstadoCita().equals(estado)) {
                pilaFiltrada.push(cita);
            }
        }
        return pilaFiltrada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ordenarPor;
    private javax.swing.JTable tablaCitas;
    // End of variables declaration//GEN-END:variables
}
