/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_edd.GUI;

import com.mycompany.proyecto_edd.Odontologo;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class RegistroOdontologo extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public RegistroOdontologo() {
        initComponents();
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        
        jButton1.putClientProperty("JComponent.roundRect", true); 
        jButton1.putClientProperty("JButton.arc", 20); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        date = new com.raven.datechooser.DateChooser();
        bg = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenidoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        fechanacimiento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nacionalidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        provincia = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1.putClientProperty("JButton.arc", 25);
        especialidad = new javax.swing.JComboBox<>();

        jLabel10.setText("jLabel10");

        date.setForeground(new java.awt.Color(2, 69, 122));
        date.setTextRefernce(fechanacimiento);

        setMinimumSize(new java.awt.Dimension(745, 440));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(745, 500));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(745, 500));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(745, 500));

        contenidoPanel.setBackground(new java.awt.Color(255, 255, 255));
        contenidoPanel.setMinimumSize(new java.awt.Dimension(745, 700));
        contenidoPanel.setName(""); // NOI18N
        contenidoPanel.setPreferredSize(new java.awt.Dimension(745, 700));
        contenidoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        jLabel1.setText("Registro de nuevo odontólogo");
        contenidoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 14, 449, -1));

        jPanel1.setBackground(new java.awt.Color(9, 140, 239));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS PERSONALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        contenidoPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 64, 660, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("DNI:");
        contenidoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 101, 71, -1));

        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });
        contenidoPanel.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 131, 209, 27));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setText("Nombres:");
        contenidoPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 176, 100, 25));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Apellidos:");
        contenidoPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 252, 101, 25));
        contenidoPanel.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 207, 209, 27));
        contenidoPanel.add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 283, 209, 27));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Sexo:");
        contenidoPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 328, 61, 25));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        contenidoPanel.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 359, 109, 27));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("Fecha de nacimiento:");
        contenidoPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 404, -1, 25));
        contenidoPanel.add(fechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 435, 209, -1));

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        contenidoPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 435, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setText("Nacionalidad:");
        contenidoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 101, 208, -1));

        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });
        contenidoPanel.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 205, 253, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel11.setText("Ciudad:");
        contenidoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 175, 126, -1));
        contenidoPanel.add(nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 131, 253, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setText("Provincia:");
        contenidoPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 249, 146, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel13.setText("Dirección:");
        contenidoPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 323, 146, -1));
        contenidoPanel.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 427, 253, -1));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setText("Teléfono:");
        contenidoPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 397, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogoDatosPersonales.png"))); // NOI18N
        contenidoPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, 331));
        contenidoPanel.add(provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 279, 253, -1));
        contenidoPanel.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 359, 253, -1));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel16.setText("Especialidad");
        contenidoPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 146, -1));

        jButton2.setBackground(new java.awt.Color(2, 69, 122));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ENVIAR");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        contenidoPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 190, 60));


        especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ortodoncia", "Periodoncia", "Endodoncia", "Prostodoncia", "Cirugía Oral" }));
        especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadActionPerformed(evt);
            }
        });
        contenidoPanel.add(especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 250, -1));

        jScrollPane2.setViewportView(contenidoPanel);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        date.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Obtener datos de los campos
        String dniR = dni.getText().trim();
        String nombresR = nombres.getText().trim();
        String apellidosR = apellidos.getText().trim();
        String sexoR = sexo.getSelectedItem().toString();
        String fechaNacimientoR = fechanacimiento.getText().trim(); // Si fechanacimiento es JTextField
        String nacionalidadR = nacionalidad.getText().trim();
        String ciudadR = ciudad.getText().trim();
        String provinciaR = provincia.getText().trim();
        String direccionR = direccion.getText().trim();
        String telefonoR = telefono.getText().trim();
        String especialidadR = especialidad.getSelectedItem().toString();

        // 2. Validación básica
        if (dniR.isEmpty() || nombresR.isEmpty() || apellidosR.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar los campos obligatorios.");
            return;
        }

        // 3. Crear odontólogo
        Odontologo nuevo = new Odontologo(
            nombresR, apellidosR, especialidadR, dniR, sexoR, direccionR, telefonoR,
            fechaNacimientoR, ciudadR, provinciaR, nacionalidadR
        );

        // 4. Guardar
        Odontologo.agregarOdontologoArchivo(nuevo);

        javax.swing.JOptionPane.showMessageDialog(this, "Odontólogo registrado correctamente.\nID asignado: " + nuevo.getIdOdontologo());
        limpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limpiarCampos() {
        dni.setText("");
        nombres.setText("");
        apellidos.setText("");
        sexo.setSelectedIndex(0);
        fechanacimiento.setText(""); 
        nacionalidad.setText("");
        ciudad.setText("");
        provincia.setText("");
        direccion.setText("");
        telefono.setText("");
        especialidad.setSelectedIndex(0);
    }

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField ciudad;
    private javax.swing.JPanel contenidoPanel;
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JComboBox<String> especialidad;
    private javax.swing.JTextField fechanacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField provincia;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
